import os
import time
print("Installing and setting up event")
time.sleep(5)
os.system("sudo apt install")
os.system("npm init -y")
os.system("npm install electron")
print("Removeing unsed files")
time.sleep(5)
os.system("rm main.js")
os.system("rm package-lock.json")
os.system("package.json")
print("Adding files")
time.sleep(5)
os.system("wget https://raw.githubusercontent.com/HttpAnimation/FYCELE/main/main.js")
os.system("wget https://raw.githubusercontent.com/HttpAnimation/FYCELE/main/package-lock.json")
os.system("wget https://raw.githubusercontent.com/HttpAnimation/FYCELE/main/package.json")
os.system("wget https://raw.githubusercontent.com/HttpAnimation/FYCELE/main/start.py")
os.system("mkdir FYC")
print("Put your fyc files in the folder FYC on the root dir NO SUB FOLDER it should look like this")
print("httpanimatins@pop-os:~/Downloads/AWAWAW$ ls")
print("FYC  install.py  main.js  node_modules  package.json  package.json.1  package-lock.json")
time.sleep(5)
print("Once you put in the FYC files run start.py to start or run | npm start")